from gcg.schemas.config.base import *
from gcg.schemas.config.ios.ios_base import *
from gcg.schemas.ios_bgp import *
from gcg.schemas.ios_vpls import *
from gcg.schemas.ios_evpn import *
from gcg.schemas.te_tunnels import *
from gcg.schemas.ios_vpls import *
from gcg.schemas.config import *
from gcg.schemas.config.linux import *
from gcg.schemas.schema_request import *